### PR TITLE
Enable packit for `main` branch

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
Enable packit builds for the main branch.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
PTAL @lsm5 
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
> @saschagrunert I'm cool with this but do we actually need the `trigger: commit` ? IIUC, it triggers builds after the commit is done, which is already being done by the webhook on `rhcontainerbot/podman-next` copr. Correct me if I'm wrong.

I assume we have to override `trigger: pull_request` from the above `&copr` link.

I got the example from https://packit.dev/docs/configuration/#packit-service-jobs

**Comment by lsm5** [comment]
> > @saschagrunert I'm cool with this but do we actually need the `trigger: commit` ? IIUC, it triggers builds after the commit is done, which is already being done by the webhook on `rhcontainerbot/podman-next` copr. Correct me if I'm wrong.
> 
> I assume we have to override `trigger: pull_request` from the above `&copr` link, so yes?! thinking
> 
> I got the example from https://packit.dev/docs/configuration/#packit-service-jobs

@saschagrunert i've pinged the packit people to understand `trigger: commit` cause right now I find it redundant along with the prior webhook. But if you wanna go ahead, by all means :slightly_smiling_face:  . If things blow up we'll soon find out :smile:

**Comment by saschagrunert** [comment]
Sounds good, PTAL @haircommander @rphillips

**Comment by lsm5** [comment]
so packit guys showered some knowledge. So, `trigger: commit` serves the same purpose as the webhook to `rhcontainerbot/podman-next` but with some additional status reporting on github itself. So, I think we can remove the webhook but we should also mention the copr project where the `after-commit` build should be sent to.

**Comment by haircommander** [comment]
oops did I merge too early

**Comment by lsm5** [comment]
na ... there can be another PR :D

**Comment by lsm5** [comment]
only difference with `trigger: commit` would be `project: podman-next` and then we disable the earlier webhook

**Comment by lsm5** [comment]
> only difference with `trigger: commit` would be `project: podman-next` and then we disable the earlier webhook

@saschagrunert webhook disabled. if you wanna do a new PR with the `project` change, please go ahead.

**Pull request merged**
