### PR TITLE
Revert "test: add stress test for ExecSyncRequests"

### PR DESCRIPTION
**Pull request by haircommander**
This reverts commit d8663cfc65658a5253500c8d5f7493c64c4c8ae5.

I did not mean to include it in my other PR

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by saschagrunert** [comment]
Is this because of the multi threaded runtime:
```
  Expected
      <uint32>: 3248
  to be <
      <int>: 230
  In [JustAfterEach] at: /home/runner/work/conmon-rs/conmon-rs/pkg/client/client_test.go:100
```

**Comment by haircommander** [comment]
hm tried reverting that too

**Comment by haircommander** [comment]
well that's worse

**Comment by saschagrunert** [comment]
Ultra strange, do it may also be related to the changed channels :thinking:

**Comment by haircommander** [comment]
oh darn so I bet what happened was since this PR was included, the only test we tested was this one, and the others were actually totally broken. I'll play around today and try to fix everything or find what to revert

**Comment by haircommander** [comment]
we should merge this to prevent other regressions, at least

**Pull request merged**
