### PR TITLE
Bump to v0.5.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### What this PR does / why we need it:
Update to v0.5.0.
#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
/hold 
for https://github.com/containers/conmon-rs/issues/1043

**Comment by saschagrunert** [comment]
/unhold

@haircommander PTAL, I need this to get https://github.com/containers/conmon-rs/pull/1042 working

**Comment by haircommander** [comment]
would you mind rebasing to have the bump commit be after the userns one?

**Comment by saschagrunert** [comment]
> would you mind rebasing to have the bump commit be after the userns one?

Yep, done

**Pull request merged**
