### PR TITLE
Change default from localhost to 127.0.0.1

### PR DESCRIPTION
**Pull request by bitoku**
#### What type of PR is this?

/kind other

#### What this PR does / why we need it:

This PR changes the default tracing endpoint to 127.0.0.1 to align with the cri-o change.

#### Which issue(s) this PR fixes:

Fixes a part of https://github.com/cri-o/cri-o/issues/7448

#### Does this PR introduce a user-facing change?

```release-note
Use 127.0.0.1 as the new default for tracing endpoint.
```

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
@bitoku CI seems to hang, do you mind a rebase?

**Comment by kwilczynski** [comment]
Can't /close and /reopen to kick the tires on the CI. :smile:

**Pull request merged**
