### PR TITLE
Bump to 0.6.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
There are a bunch of changes between 0.5.1 and main: https://github.com/containers/conmon-rs/compare/v0.5.1...main

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
/hold

For discussion.
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
personally , I would call this a 0.6.0. We're also approaching v1.0.0-rc territory, but I think we should wait for @mgjm 's exec work first

**Comment by saschagrunert** [comment]
Good, switched to v0.6.0.

**Comment by rphillips** [comment]
lgtm

The hold can be removed.

**Pull request merged**
