### PR TITLE
Add usage/release documentation

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind documentation

#### Which issue(s) this PR fixes:

None

#### Special notes for your reviewer:

We require a new CRI-O v1.25.2 to be released including the backport for conmon-rs v0.4.0: https://github.com/cri-o/cri-o/pull/6359

#### Does this PR introduce a user-facing change?

```release-note
Added usage documentation.
```

### CODE REVIEW

**Comment by saschagrunert** [comment]
cc @harche @wgahnagl

**Comment by saschagrunert** [comment]
@rphillips @haircommander PTAL

**Comment by rphillips** [comment]
@saschagrunert can you add a blurb on how to do a release?

**Comment by rphillips** [comment]
Thanks! lgtm
@haircommander

**Comment by saschagrunert** [comment]
> @saschagrunert can you add a blurb on how to do a release?

Done :+1:

**Pull request merged**
