### PR TITLE
Add config structure

### PR DESCRIPTION
**Pull request by haircommander**
based heavily on https://github.com/containers/conmon/commit/184682ba89759a91f0bc90c0ed1fdc279a6a0afb, but only including the fields that will be needed for a pod level conmon, rather than a conmon per container

(requires https://github.com/containers/conmon-rs/pull/1)

### CODE REVIEW

**Comment by haircommander** [comment]
I am pretty sure all remaining cli flags for conmon can be implemented as GRPC args, as they're more pertinent to the individual container create/exec/restore

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
Unfortunately I cannot merge within this repository.

**Comment by rhatdan** [comment]
@haircommander @saschagrunert You are both admin of this Repo now.

**Comment by saschagrunert** [comment]
Thanks @rhatdan!

**Pull request merged**
