### PR TITLE
Bump Rust to v1.69.0

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
We can also remove the build constraints from the `Cargo.toml` file since we have updated them in the past.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
Updated latest required Rust version to v1.69.0
```

### CODE REVIEW

**Comment by rphillips** [comment]
@saschagrunert needs a rebase

**Comment by saschagrunert** [comment]
Rebased :+1:

**Pull request merged**
