### PR TITLE
Add OOM integration test

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind ci

#### What this PR does / why we need it:
I also refactored some logs to automatically trace the PID as well as sanitized them.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
The new test cases:

```
ConmonClient CreateContainer
  should catch out of memory (oom) events with terminal
  /home/runner/work/conmon-rs/conmon-rs/pkg/client/client_test.go:135
2022-05-13T09:09:27.337145Z  INFO conmon::server: 166: Received SIGINT
2022-05-13T09:09:27.338161Z  INFO conmon::server: 120: Using stdout logger
2022-05-13T09:09:27.338182Z  INFO conmon::server: 130: Set log level to: debug
2022-05-13T09:09:27.339977Z DEBUG conmon::rpc: 50: Got a version request
2022-05-13T09:09:27.340533Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}: conmon::rpc: 74: Got a create container request
2022-05-13T09:09:27.340586Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}: conmon::terminal: 61: Creating new terminal
2022-05-13T09:09:27.340716Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:listen: conmon::terminal: 137: Listening terminal socket on /tmp/conmon-term-1Xxeio4.sock
2022-05-13T09:09:27.340936Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}: conmon::rpc: 83: PID file is /tmp/conmon-client4[275](https://github.com/containers/conmon-rs/runs/6420332913?check_suite_focus=true#step:11:275)970848/pidfile
2022-05-13T09:09:27.340954Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}: conmon::server: 240: Runtime args "--root=/tmp/conmon-client4275970848/root create --bundle /tmp/conmon-client4275970848 --pid-file /tmp/conmon-client4275970848/pidfile --console-socket=/tmp/conmon-term-1Xxeio4.sock e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf"
2022-05-13T09:09:27.340973Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:promise: conmon::cri_logger: 48: Initializing CRI logger in path /tmp/conmon-client4275970848/log
2022-05-13T09:09:27.341425Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:promise: conmon::terminal: 100: Waiting for terminal socket connection
2022-05-13T09:09:27.348721Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:listen: conmon::terminal: 151: Got terminal socket stream: PollEvented { io: Some(UnixStream { fd: FileDesc(OwnedFd { fd: 13 }), local: "/proc/self/fd/11/conmon-term-1Xxeio4.sock" (pathname), peer: (unnamed) }) }
2022-05-13T09:09:27.375075Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:listen: conmon::terminal: 174: Removing socket path /tmp/conmon-term-1Xxeio4.sock
2022-05-13T09:09:27.375199Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:listen: conmon::terminal: 177: Shutting down receiver stream
2022-05-13T09:09:27.375214Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:listen: conmon::terminal: 185: Received terminal file descriptor
2022-05-13T09:09:27.375221Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:listen: conmon::terminal: 188: Changing terminal settings
2022-05-13T09:09:27.375260Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:listen: conmon::terminal: 226: Shutting down listener thread
2022-05-13T09:09:28.298365Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:promise:watch{pid=6017}:task:oom_handling_cgroup_v1{pid=6017}: conmon::oom_watcher: 309: Using cgroup path: /proc/6017/cgroup
2022-05-13T09:09:28.299439Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:promise:watch{pid=6017}:task: conmon::oom_watcher: 94: Setup cgroup v1 oom handling path="/sys/fs/cgroup/memory/system.slice/runner-provisioner.service/e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf/memory.oom_control"
2022-05-13T09:09:28.300149Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:promise:watch{pid=6017}:task: conmon::oom_watcher: 121: Successfully setup cgroup v1 oom detection
Waiting for OOM exit path to exist
Waiting for OOM exit path to exist
Waiting for OOM exit path to exist
Waiting for OOM exit path to exist
2022-05-13T09:09:31.669855Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:promise:watch{pid=6017}:task: conmon::oom_watcher: 132: Got oom event
2022-05-13T09:09:31.669896Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:promise:watch{pid=6017}:task:write_oom_file: conmon::oom_watcher: [276](https://github.com/containers/conmon-rs/runs/6420332913?check_suite_focus=true#step:11:276): Writing OOM file: /tmp/conmon-client4275970848/oom_exit
2022-05-13T09:09:31.670044Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:promise:watch{pid=6017}:task: conmon::oom_watcher: 136: Successfully wrote oom files
2022-05-13T09:09:31.670054Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:promise:watch{pid=6017}:task: conmon::oom_watcher: 144: Done watching for ooms
VmRSS for server is 196
2022-05-13T09:09:32.427510Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:promise:watch{pid=6017}:wait_for_exit_code: conmon::child_reaper: 332: Signaled
2022-05-13T09:09:32.4[277](https://github.com/containers/conmon-rs/runs/6420332913?check_suite_focus=true#step:11:277)99Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:listen:read_loop: conmon::container_io: 245: Stopping read loop
2022-05-13T09:09:32.428445Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:promise:watch{pid=6017}: conmon::child_reaper: 293: Sending exit struct to channel: ExitChannelData { exit_code: 137, oomed: true, timed_out: false }
2022-05-13T09:09:32.428880Z DEBUG create_container{container_id="e388beccf6761109b0a3b850199f6311ca34ca3fdb671c783aafe1540d0db0cf" uuid="4d244a31-43be-4081-9884-765931e0b45f"}:promise:watch{pid=6017}: conmon::child_reaper: 297: Write to exit paths: /tmp/conmon-client4275970848/exit
------------------------------
• [SLOW TEST] [5.161 seconds]
ConmonClient
/home/runner/work/conmon-rs/conmon-rs/pkg/client/client_test.go:20
  CreateContainer
  /home/runner/work/conmon-rs/conmon-rs/pkg/client/client_test.go:52
    should catch out of memory (oom) events with terminal
    /home/runner/work/conmon-rs/conmon-rs/pkg/client/client_test.go:135

```

#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
nice cleanup and test! LGTM

**Comment by saschagrunert** [comment]
@rphillips PTAL

**Pull request merged**
