### PR TITLE
add release packaging

### PR DESCRIPTION
**Pull request by rphillips**
Adds release packaging workflows.

```release-note
NONE
```

### CODE REVIEW

**Comment by rphillips** [comment]
This is ready for review... I can't test this until we merge and tag a release. Tested locally and it works.

**Comment by haircommander** [comment]
LGTM, @saschagrunert LGYT?

**Comment by rphillips** [comment]
pushed a small fix to the GH action that I just caught.

**Review by saschagrunert — APPROVED** [review]
Thanks!

**Pull request merged**
