### PR TITLE
Sanitize oom watcher logs

### PR DESCRIPTION
**Pull request by saschagrunert**
#### What type of PR is this?

/kind cleanup

#### What this PR does / why we need it:
We now apply a bunch of rules, for example:

- Start logs upper case
- Remove redundant information like the PID (already part of the tracing span)
- Do not print "Error" for error logs, since the level already tells us
  that it's an error.

#### Which issue(s) this PR fixes:

None
#### Special notes for your reviewer:
None
#### Does this PR introduce a user-facing change?

```release-note
None
```

### CODE REVIEW

**Comment by haircommander** [comment]
LGTM

**Comment by saschagrunert** [comment]
@haircommander it looks like that tide is not active yet for that project :thinking:

**Pull request merged**
